# Generated by Django 4.0.6 on 2022-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=200, verbose_name='Название лабы')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
