# Generated by Django 4.0.6 on 2022-11-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_laboratorywork_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorywork',
            name='upload',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
